services:
  mysql-master:
    image: mysql:8.0.43-debian
    restart: always
    environment:
      MYSQL_ROOT_PASSWORD: root
      MYSQL_DATABASE: board
      MYSQL_USER: board-user
      MYSQL_PASSWORD: user1234!
    ports:
      - "13306:3306"
    volumes:
      - db_data_master:/var/lib/mysql
    command:
      --server-id=1
      --log-bin=mysql-bin
      --binlog-format=row
    networks:
      - mysql-network

  mysql-slave:
    image: mysql:8.0.43-debian
    restart: always
    environment:
      MYSQL_ROOT_PASSWORD: root
      MYSQL_DATABASE: board
      MYSQL_USER: board-user
      MYSQL_PASSWORD: user1234!
    ports:
      - "13307:3306"
    volumes:
      - db_data_slave:/var/lib/mysql
    command:
      --server-id=2
      --log-bin=mysql-bin
      --binlog-format=row
    networks:
      - mysql-network
volumes:
  db_data_master:
  db_data_slave:

networks:
  mysql-network:
    driver: bridge